Implement mates between connectors, better autogeneration
wireviz/WireViz pull request #186
Opened 2020-10-22 16:25 UTC by formatc1702

This is a sandbox to try an implementation of #134 and #184, with possible effects for #142 and #185.

- Discussion regarding the new syntax for mating connectors happens in  #134.
- Discussion regarding the new syntax for auto-generated components happens in #184.

This PR will try to reflect the results in those discussions.

The implementation will work towards being able to parse the included `test/test1.yml` and produce the expected result. This test file will try to reflect and test any related new features suggested in the discussions.

No detailed code review is necessary at the moment, consider this a work in progress;

2020-10-24 13:30 UTC, formatc1702 commented
The current state is able to parse all current examples/tutorials/demos (only minor changes to the source file necessary), as well as all test files, inspired by the discussions in the issues mentioned above. See `tests/` directory for sources.

<details>
 <summary>See renderings</summary>

## Test 1

![test1](https://user-images.githubusercontent.com/2447251/97082988-af844800-160d-11eb-872a-8350cc072628.png)

## Test 2

Test 2![test2](https://user-images.githubusercontent.com/2447251/97082990-b27f3880-160d-11eb-8c22-e8fbcb4a2910.png)

## Test 3

![test3](https://user-images.githubusercontent.com/2447251/97082992-b57a2900-160d-11eb-871f-d1f43cfd9a76.png)

## Test 4

![test4](https://user-images.githubusercontent.com/2447251/97082993-b7dc8300-160d-11eb-9db7-a272e017385a.png)

## Test 9

![test9](https://user-images.githubusercontent.com/2447251/97082999-bb700a00-160d-11eb-9089-1f81cff691e3.png)


</details>

2021-03-20 11:01 UTC, formatc1702 commented
Even though I have not worked on this feature for a while, I have been using it in practice and it has proven quite robust.

I would like to request a review of the code, and I am open for ideas on how to solve the [open TODO](https://github.com/formatc1702/WireViz/pull/186/files#diff-4868ecda012df03682c97a37b93917a698aeec9adac351873f6d78cf2afc908cR132-R138)...

@kvid how do you feel about this?

2021-10-13 17:18 UTC, formatc1702 commented
Thanks @awb1015 for the feedback!

Usually I've waited for @kvid's approval before merging into `dev`, since he's quite good at catching edge cases, improving the code quality and providing generally valuable feedback. But as you can see by my previous comment, this might be a good PR to try out a new merging strategy, with post-hoc review and improvement.
I realize this would be an unilateral decision by me, and might be seen as hypocritical since kvid and others have had to wait for months for me to react to PRs and issues in the past, so I have been shy about this approach so far.

2021-10-13 21:08 UTC, formatc1702 commented
Yes please, a setof files for a minimal working example will be really helpful.

2021-10-14 16:15 UTC, formatc1702 commented
Please try the updated code; your bug should be fixed in 02a800abef3f35bdc4f8bbcafd9f50309a7cbe17.

Root cause:
- #229 changed the way connections between components are handled by internally assigning unique IDs to the "ports" where wires (and now arrows) attach to connectors.
- This mapping happened inside the `Harness.connect()` function, which is called when attaching wires.
  Arrows between pins use `Harness.add_mate_pin()` instead, which did not implement the mapping
- In addition, `Harness.create_graph()` had to be adjusted to add `+1` to convert the [0-indexed] internal IDs to 1-indexed port IDs.
  - The decision to use 1-indexed ports in GraphViz was taken so that port IDs would match the typical use case with connector pin numberings starting at 1
  - This is also the reason why the bug only appeared with your custom pin numbering.

2021-12-18 03:09 UTC, kvid requested changes
Sorry about this long period without any reply. These changes looks good. I only have a couple of suggestions.

2022-08-05 16:49 UTC, formatc1702 commented
All comments have been addressed inside https://github.com/formatc1702/WireViz/pull/251.

2022-10-18 12:08 UTC, SeanDS commented
This looks promising for my use case. Would it be possible to group together the two sides of the mate in one box, instead of those arrows? I'm thinking a box with numbering on both left and right sides and labels between indicating the name of the pin pair. As I noted in #295 there are certain connectors where pin numberings change on the same conductor, so these numbers would ideally not be fixed.

2023-06-07 17:11 UTC, merged

2024-05-30 08:37 UTC, martinrieder commented
It seems that the user-configurable autogeneration character from https://github.com/wireviz/WireViz/commit/45bcc1dd458a953ba1b2d6fe5ccd5ae866135661 became an undocumented feature.

2024-05-30 19:13 UTC, kvid commented
@martinrieder wrote:
> It seems that the user-configurable autogeneration character from [45bcc1d](https://github.com/wireviz/WireViz/commit/45bcc1dd458a953ba1b2d6fe5ccd5ae866135661) became an undocumented feature.

You are right, it's not mentioned in the docs, but I don't know if it might be due to lack of testing, unstability, just forgotten, or something else. Maybe @formatc1702 remembers any reason for omitting it from the docs?

2024-06-07 15:07 UTC, formatc1702 commented
Thanks. I have added a line in the syntax description (in the `dev` branch) for now so it is not forgotten, see 590504130c5e878c51df571974ee31e6f01b3a53.

It's a good idea to do some testing as suggested; then the documentation can be expanded accordingly.

2024-06-07 18:24 UTC, martinrieder commented
@kvid wrote:
> Edit: If you @martinrieder have the time, maybe you could test this optional feature with a few different values, and verify the intended effect? Does it only work with a single character, or also with longer strings? Do you observe any unfortunate side-effects with certain characters/strings? Please store a few YAML input test cases for future regression testing.

I can do that. I guess that quotation characters could be problematic in this case. For sure, there should be a check to not accept an empty string here.