Fix Exception Handling in _get_yaml_data_and_path(...)
wireviz/WireViz pull request #392
Opened 2024-06-20 11:28 UTC by martinrieder

Add ValueError and OSError where `e.errno` is `None` to Exception Handling of `_get_yaml_data_and_path()`

**This PR is amending fixes for the following issues based on #250 and #318.**
- https://github.com/wireviz/WireViz/pull/318#pullrequestreview-1457016602
  describing 80000 character YAML input raising `ValueError`
- https://github.com/wireviz/WireViz/issues/391#issuecomment-2180419249 
  describing `OSError: _getfinalpathname: path too long for Windows` 

```
# if inp is a long YAML string, Pathlib will raise OSError [errno.ENAMETOOLONG]
# in Windows, ValueError or OSError [errno.EINVAL or None] also might be raised
# when trying to expand and resolve it as a path (depending on the Python version)
# Catch these specific errors, but raise any others
```
 
`master` contains #250 from d7d7854bce39881a970b54e3522d9293441c5ce1: Consolidate wireviz.parse() to handle Path, str and Dict as input

https://github.com/wireviz/WireViz/blob/954c4f5f92b1d0531f6af0c318c60786b7906d42/src/wireviz/wireviz.py#L415

`release/v0.4.1-rc` contains #318 at 6f9007f45d48cc65f3469b362976bb53ac1cd7e0: Use portable OS error codes so program doesn't crash

https://github.com/wireviz/WireViz/blob/ba84c54382b540dfa50dcd5e3592917abdbfb1f8/src/wireviz/wireviz.py#L419

Due to the following https://github.com/wireviz/WireViz/pull/246#issuecomment-1206635845, this is a bugfix only, waiting to be resolved by #251. 
> All comments have been addressed inside #251 or are no longer relevant after 251 is applied

_References_
- #365
  - #391
    #392
  - #344
    #346
  - #318
- #190
  #246
- #250
  #251

2024-06-26 19:04 UTC, kvid commented
@martinrieder wrote:
> I noticed that a similar issue has been found by @kvid in [#318 (review)](https://github.com/wireviz/WireViz/pull/318#pullrequestreview-1457016602) a year ago. Could you please check this again?
> 
> It seems that behavior changes with different Python versions. The referred one uses `ValueError` in 3.9, while it is now reported as `OSError` in 3.12.

I can confirm that I still get `ValueError: _getfinalpathname: path too long for Windows` when trying WireViz on input YAML with 80000 character dummy string in Python 3.10.4 at Windows 10. It's not a very likely use case, but demonstrates a possible exception when trying to use random strings as a path. This edge case is resolved by including `ValueError` in the list of exceptions to catch.

2024-06-27 00:40 UTC, kvid commented
> what does errno evaluate to in that case?

An `OSError` exception has `errno`, but `ValueError` has not.

> Which version of Pathlib are you running?

`pathlib` is a system library included in (and identified by) the Python 3.10.4 installation in my case. System libraries doesn't have separate version numbers AFAIK.

> 
> BTW: I do not consider running a huge YAML file to be that unusual. If a library of connectors is contained in the templates section, file size can increase quickly.

I agree to that, but my 80000 character test input was only a single long string, and that is a bit unusual. However, I just now added my 80000 character as one of the attributes of a connector in a valid WireViz YAML file, and the same ValueError was raised, so you are probably right it also can happen with a huge template section.

2024-06-27 08:17 UTC, kvid commented
> > I suggest you include `ValueError` like this:
> > ```python
> >         except (FileNotFoundError, OSError, ValueError) as e:
> > ```
> 
> Additionally, the if clause needs to be adapted, so that the exception is also raised.

No, the `if` only needs to raise other `OSError` exceptions than the identified `errno` values.

> 
> My proposal to add some "band-aid" the fix:
> 
> * **If `inp` contains newline characters, treat it as YAML**

As I wrote a year ago in point 4 of https://github.com/wireviz/WireViz/pull/318#pullrequestreview-1457016602 that you referred to above, this is exactly what is already implemented in #251.

Catching more exceptions here is just a quick band-aid to avoid most errors until the more thorough fix in #251.

> * Else pass it to Pathlib and catch its exceptions
> * Raise any unexpected exceptions

No expected exceptions to catch after the #251 changes, so they are all raised normally.

> * Fall back to YAML parsing on FileNotFoundError etc.

No special catching of these exceptions are needed.

> 
> What do you think about treating all multi-line strings as YAML?

I agree, and #251 is the first to be merged after releasing the collections of quick-fixes.

> 
> Besides bugfixing, would printing an error message if it is neither an existing file nor valid YAML provide a more user-friendly behavior instead of simply raising an exception?

See #207

2024-06-28 10:20 UTC, kvid commented
@formatc1702 seems to prefer not referring to issues or PRs in the source code - see https://github.com/wireviz/WireViz/pull/264#discussion_r1319052618

Referring to them in the body of commit messages is OK and often useful, though.

I therefore suggest removing the two trailing comments including issue references. Instead I suggest expanding the comment block to explain the latest additions like this:
```py
    # if inp is a long YAML string, Pathlib will raise OSError: [errno.ENAMETOOLONG]
    # (in Windows, it seems ValueError or OSError [errno.EINVAL or None]
    # also might be raised in some cases - depending on the Python version)
    # when trying to expand and resolve it as a path.
    # Catch these errors, but raise any others
```

2024-06-28 18:25 UTC, kvid commented
@martinrieder wrote:
> Thanks. I will update the PR accordingly.
> 
> I discovered an additional OS-specific bug with `expanduser()` that arises when the file name contains a tilde `~` character. Should I include a fix for this as well, even though it is a separate issue?

If the fix is similar to what is already discussed (catching an extra `Exception` class or `OSError.errno` value), then I see no harm in including also that fix in this PR - just update the PR title and description to cover all sub-issues.

Please [use the imperative mood in your commit subject lines](https://cbea.ms/git-commit/#imperative) as recommended in the [contribution guidelines](https://github.com/wireviz/WireViz/blob/v0.4/docs/CONTRIBUTING.md#hints) and I think the PR title should follow the same recommendation as for commit subject lines, because a squash commit will normally use the PR title as subject line.

2024-06-28 21:05 UTC, kvid commented
I'm sorry for being unclear. When I wrote "_update the PR title and description to cover all sub-issues_", I didn't mean all details should be in the title. Please read all the commit recommendations at the page I linked to above. The subject line should be a short summary, preferably limited to 50 characters and never more than 72. Use the body for details.

2024-07-01 17:36 UTC, formatc1702 commented
Thanks for digging into these more obscure issues despite my limited availability. It seems like a very minor code change with multiple positive effects, good job :) I assume it's ready for merge but have requested review just to be sure.

2024-07-01 19:36 UTC, kvid commented
@martinrieder wrote:
> [...]
> I discovered an additional OS-specific bug with `expanduser()` that arises when the file name contains a tilde `~` character. Should I include a fix for this as well, even though it is a separate issue?

Didn't you include a fix for this? I can't see any more code additions than what we discussed before you mentioned this last issue.

Or does the fix involve huge code changes that is clearly out of scope for this PR?

2024-07-01 23:04 UTC, kvid commented
At Linux it's normal to evaluate a path with a leading `~Martin` to the home folder of a user named `Martin`, and it seems Python tries to make this work in a similar fashion at Windows. Se also https://docs.python.org/3/library/os.path.html#os.path.expanduser
and https://docs.python.org/3/library/pathlib.html#pathlib.Path.expanduser

If I understand your description correctly, it seems to work as designed. You get an exception because there is no user named `demo01.yml` at your PC, and hence no home folder named `C:\\Users\\demo01.yml`.

2024-07-03 20:36 UTC, kvid requested changes
- `build_examples.py` runs without errors, and produces the expected results (diffs on version numbers and image absoulute paths are normal).
- My `a-80k.yml` from https://github.com/wireviz/WireViz/pull/392#issuecomment-2192442165 is processed without errors, and produces the expected result.
- I'm not able to verify the fix for #391 because I'm not able to reproduce the reported error with `YMLFILE.txt` from #391 (I've tried with Python 3.9.13 and 3.12.4 because 3.12.3 is no longer available from Microsoft Store). I get no errors both before and after changes in this PR.
- I suggest a simple squash and merge with a summary of the two resolved issues in the resulting commit body.

2024-07-03 20:36 UTC, kvid commented on src/wireviz/wireviz.py
> +            # Catch these specific errors, but raise any others
I feel your latest rewriting of these comments might have unintentionally changed the meaning a bit, so I suggest a new rewriting that hopefully is easier to understand:
```suggestion
            # if inp is a long YAML string, Pathlib will normally raise
            # FileNotFoundError or OSError(errno = ENAMETOOLONG) when
            # trying to expand and resolve it as a path, but in Windows
            # might ValueError or OSError(errno = EINVAL or None) be raised
            # instead in some cases (depending on the Python version).
            # Catch these specific errors, but raise any others.
```

2024-07-04 16:35 UTC, kvid approved these changes

2024-07-04 16:36 UTC, merged